### ISSUE TITLE
Exposure time not properly loaded via load_arf for XMM-Newton Responses

### ISSUE THREAD

**Issue by bjricketts** [matteolucchini1/nDspec#11]
Using load_arf doesn't set the correct exposure time when using XMM-Newton responses. This may be caused by differences in where the exposure time is saved for different datasets.

**Comment by matteolucchini1** [comment]
Following our chat, this is normal since the exposure is (typically) stored in the .pha file

**Comment by bjricketts** [comment]
This has been resolved by the addition of a set_exposure_time method in the Response class.
