### ISSUE TITLE
Tests need updating

### ISSUE THREAD

**Issue by bjricketts** [matteolucchini1/nDspec#17]
Current tests sometimes make reference to old methods that no longer exist. It would be good to make sure all tests are up to date and successfully run.

**Comment by bjricketts** [comment]
Also, if a file is required for a test to pass (such as a specific response file), we should also make sure those are in the github.

**Comment by matteolucchini1** [comment]
Tests updated in [https://github.com/matteolucchini1/nDspec/commit/64ada66eeb2e67cae8f1859dd7610ad6d71cd26b](this) commit. The files are already in the repo in the tests/data/ folder.
