### ISSUE TITLE
Ignore channels in response matrix

### ISSUE THREAD

**Issue by bjricketts** [matteolucchini1/nDspec#4]
It would be useful to have a way of ignoring energy channels in response matrices for when convolving it with a model output with a smaller (but otherwise identical in terms of energy bins) energy grid than the complete response.

Either adjusting this to be a change to the response matrix itself or a response matrix can ignore channels as specified when a model is evaluated would work.

**Comment by matteolucchini1** [comment]
For future reference, I should also a) do this for all operators, not just response matrices and b) allow the FourierProduct operator to ignore a range of frequencies

**Comment by bjricketts** [comment]
I'm currently linking the active branch dev_response_utils with a somewhat stop gap solution to this for Response matrices. We should revise this to be in-line with the above suggestion eventually.
